version: "3"

services:

  database:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: catalog1
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    #banco de dados precisa iniciar para o app rodar
    image: lucas10sh/restapi
    build: "./PROJETO-JOAQUIM"
    depends_on:
      - database
    ports:
      - 8080:8080
    container_name: java-api
    environment:
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: catalog1
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      # SPRING_DATA_MONGODB_USERNAME: root
      # SPRING_DATA_MONGODB_PASSWORD: app123
      SPRING_DATA_MONGODB_DATABASE: catalog1
    stdin_open: true
    tty: true
    restart: always

volumes:
  db:
